[tool.poetry]
name = "pyzoom"
version = "0.1.0"
description = "Python wrapper for Zoom Video API"
authors = ["Mikhail Beliansky <mb@blaster.ai>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
attrs = "^19.3.0"
pyjwt = "^1.7.1"
typing-extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
